import type {
  ConfigDraft,
  McpServerDraft,
  ModelProviderDraft,
  ProfileDraft,
  ProjectDraft,
} from "@/lib/config/types";

export const SAMPLE_REVIEWED_ON = "2026-07-10";
export const SAMPLE_REFERENCE_URL = "https://developers.openai.com/codex/config-sample/";
export const CONFIG_REFERENCE_URL = "https://developers.openai.com/codex/config-reference/";
export const SUBAGENTS_REFERENCE_URL = "https://developers.openai.com/codex/subagents";
export const REPOSITORY_URL = "https://github.com/depressi0n/codex-config-viewer";
export const SAMPLE_UNSUPPORTED_TOML = [
  "[tui]",
  "notifications = false",
  "animations = true",
  "show_tooltips = true",
  "",
  "[analytics]",
  "enabled = true",
  "",
  "[feedback]",
  "enabled = true",
  "",
  "[otel]",
  "log_user_prompt = false",
  'environment = "dev"',
  'exporter = "none"',
  'trace_exporter = "none"',
  'metrics_exporter = "statsig"',
  "",
  "[windows]",
  'sandbox = "unelevated"',
  "",
  "[agents.reviewer]",
  'description = "Find correctness, security, and test risks in code."',
  'config_file = "./agents/reviewer.toml"',
  'nickname_candidates = ["Athena", "Ada"]',
  "",
  "[[skills.config]]",
  'path = "/path/to/skill/SKILL.md"',
  "enabled = false",
  "",
].join("\n");
export const VERCEL_DEPLOY_URL = `https://vercel.com/new/clone?${new URLSearchParams({
  "repository-url": REPOSITORY_URL,
  "project-name": "codex-config-viewer",
  "repository-name": "codex-config-viewer",
}).toString()}`;

export function createEmptyModelProvider(): ModelProviderDraft {
  return {
    id: "",
    name: "",
    baseUrl: "",
    wireApi: "",
    queryParams: [],
    envKey: "",
    envKeyInstructions: "",
    requiresOpenaiAuth: false,
    requestMaxRetries: "",
    streamMaxRetries: "",
    streamIdleTimeoutMs: "",
    supportsWebsockets: false,
    experimentalBearerToken: "",
    httpHeaders: [],
    envHttpHeaders: [],
    authCommand: "",
    authArgs: [],
    authCwd: "",
    authTimeoutMs: "",
    authRefreshIntervalMs: "",
    awsProfile: "",
    awsRegion: "",
  };
}

export function createEmptyMcpServer(): McpServerDraft {
  return {
    id: "",
    transport: "stdio",
    enabled: true,
    required: false,
    command: "",
    args: [],
    env: [],
    envVars: [],
    cwd: "",
    experimentalEnvironment: "",
    url: "",
    bearerTokenEnvVar: "",
    httpHeaders: [],
    envHttpHeaders: [],
    startupTimeoutSec: "",
    toolTimeoutSec: "",
    enabledTools: [],
    disabledTools: [],
    scopes: [],
    oauthResource: "",
    auth: "",
    defaultToolsApprovalMode: "",
  };
}

export function createEmptyProfile(): ProfileDraft {
  return {
    id: "",
    model: "",
    modelProvider: "",
    approvalPolicy: "",
    sandboxMode: "",
    serviceTier: "",
    ossProvider: "",
    modelReasoningEffort: "",
    planModeReasoningEffort: "",
    modelReasoningSummary: "",
    modelVerbosity: "",
    personality: "",
    modelCatalogJson: "",
    modelInstructionsFile: "",
    experimentalCompactPromptFile: "",
    toolsViewImage: false,
  };
}

export function createEmptyProject(): ProjectDraft {
  return {
    path: "",
    trustLevel: "",
  };
}

export function createEmptyDraft(): ConfigDraft {
  return {
    general: {
      model: "",
      reviewModel: "",
      modelProvider: "",
      approvalPolicy: "",
      approvalPolicyGranular: {
        sandboxApproval: false,
        rules: false,
        mcpElicitations: false,
        requestPermissions: false,
        skillApproval: false,
      },
      approvalsReviewer: "",
      allowLoginShell: false,
      sandboxMode: "",
      serviceTier: "",
      webSearch: "",
      activeProfile: "",
      modelReasoningEffort: "",
      planModeReasoningEffort: "",
      modelReasoningSummary: "",
      modelVerbosity: "",
      modelContextWindow: "",
      modelAutoCompactTokenLimit: "",
      modelAutoCompactTokenLimitScope: "",
      modelSupportsReasoningSummaries: false,
      modelCatalogJson: "",
      modelInstructionsFile: "",
      developerInstructions: "",
      compactPrompt: "",
      toolOutputTokenLimit: "",
      defaultPermissions: "",
      personality: "",
      ossProvider: "",
      cliAuthCredentialsStore: "",
      chatgptBaseUrl: "",
      openaiBaseUrl: "",
      forcedChatgptWorkspaceId: "",
      forcedLoginMethod: "",
      mcpOauthCredentialsStore: "",
      mcpOauthCallbackPort: "",
      mcpOauthCallbackUrl: "",
      projectDocMaxBytes: "",
      projectDocFallbackFilenames: [],
      projectRootMarkers: [],
      notify: [],
      experimentalCompactPromptFile: "",
      backgroundTerminalMaxTimeout: "",
      logDir: "",
      sqliteHome: "",
      fileOpener: "",
      hideAgentReasoning: false,
      showRawAgentReasoning: false,
      disablePasteBurst: false,
      windowsWslSetupAcknowledged: false,
      checkForUpdateOnStartup: false,
      suppressUnstableFeaturesWarning: false,
    },
    history: {
      persistence: "",
      maxBytes: "",
    },
    features: {
      shellTool: "",
      apps: "",
      hooks: "",
      unifiedExec: "",
      shellSnapshot: "",
      multiAgent: "",
      goals: "",
      remotePlugin: "",
      personalityFeature: "",
      fastMode: "",
      enableRequestCompression: "",
      skillMcpDependencyInstall: "",
      preventIdleSleep: "",
      memories: "",
    },
    sandboxWorkspaceWrite: {
      writableRoots: [],
      networkAccess: false,
      excludeTmpdirEnvVar: false,
      excludeSlashTmp: false,
    },
    shellEnvironmentPolicy: {
      inherit: "",
      ignoreDefaultExcludes: false,
      exclude: [],
      set: [],
      includeOnly: [],
      experimentalUseProfile: false,
    },
    tools: {
      webSearch: "",
      viewImage: false,
    },
    agents: {
      maxThreads: "",
      maxDepth: "",
      jobMaxRuntimeSeconds: "",
      interruptMessage: "",
    },
    modelProviders: [],
    mcpServers: [],
    profiles: [],
    projects: [],
  };
}

export function createSampleDraft(): ConfigDraft {
  return {
    general: {
      model: "gpt-5.6",
      reviewModel: "",
      modelProvider: "openai",
      approvalPolicy: "on-request",
      approvalPolicyGranular: {
        sandboxApproval: true,
        rules: true,
        mcpElicitations: true,
        requestPermissions: false,
        skillApproval: false,
      },
      approvalsReviewer: "",
      allowLoginShell: true,
      sandboxMode: "read-only",
      serviceTier: "",
      webSearch: "cached",
      activeProfile: "",
      modelReasoningEffort: "",
      planModeReasoningEffort: "",
      modelReasoningSummary: "",
      modelVerbosity: "",
      modelContextWindow: "",
      modelAutoCompactTokenLimit: "",
      modelAutoCompactTokenLimitScope: "",
      modelSupportsReasoningSummaries: false,
      modelCatalogJson: "",
      modelInstructionsFile: "",
      developerInstructions: "",
      compactPrompt: "",
      toolOutputTokenLimit: "",
      defaultPermissions: "",
      personality: "",
      ossProvider: "",
      cliAuthCredentialsStore: "file",
      chatgptBaseUrl: "https://chatgpt.com/backend-api/",
      openaiBaseUrl: "",
      forcedChatgptWorkspaceId: "",
      forcedLoginMethod: "",
      mcpOauthCredentialsStore: "auto",
      mcpOauthCallbackPort: "",
      mcpOauthCallbackUrl: "",
      projectDocMaxBytes: "32768",
      projectDocFallbackFilenames: [],
      projectRootMarkers: [],
      notify: [],
      experimentalCompactPromptFile: "",
      backgroundTerminalMaxTimeout: "",
      logDir: "",
      sqliteHome: "",
      fileOpener: "vscode",
      hideAgentReasoning: false,
      showRawAgentReasoning: false,
      disablePasteBurst: false,
      windowsWslSetupAcknowledged: false,
      checkForUpdateOnStartup: true,
      suppressUnstableFeaturesWarning: false,
    },
    history: {
      persistence: "save-all",
      maxBytes: "",
    },
    features: {
      shellTool: "",
      apps: "",
      hooks: "",
      unifiedExec: "",
      shellSnapshot: "",
      multiAgent: "",
      goals: "",
      remotePlugin: "",
      personalityFeature: "",
      fastMode: "",
      enableRequestCompression: "",
      skillMcpDependencyInstall: "",
      preventIdleSleep: "",
      memories: "",
    },
    sandboxWorkspaceWrite: {
      writableRoots: [],
      networkAccess: false,
      excludeTmpdirEnvVar: false,
      excludeSlashTmp: false,
    },
    shellEnvironmentPolicy: {
      inherit: "all",
      ignoreDefaultExcludes: false,
      exclude: [],
      set: [],
      includeOnly: [],
      experimentalUseProfile: false,
    },
    tools: {
      webSearch: "cached",
      viewImage: false,
    },
    agents: {
      maxThreads: "",
      maxDepth: "",
      jobMaxRuntimeSeconds: "",
      interruptMessage: "",
    },
    modelProviders: [],
    mcpServers: [],
    profiles: [],
    projects: [],
  };
}

export function createRecommendedDraft(): ConfigDraft {
  const draft = createSampleDraft();

  draft.general.approvalPolicy = "on-request";
  draft.general.sandboxMode = "workspace-write";
  draft.general.webSearch = "live";
  draft.history.persistence = "save-all";
  draft.sandboxWorkspaceWrite.networkAccess = true;
  draft.shellEnvironmentPolicy.inherit = "core";
  draft.tools.webSearch = "live";

  return draft;
}
